### ISSUE TITLE
Something missing in the readme instructions

### ISSUE THREAD

**Issue by Ricardoaraujo00** [JByfordRew/BlazorTransitionableRoute#7] opened 2022-02-22 15:14 UTC
Pasting this line in program.cs 

`builder.Services.AddScoped<BlazorTransitionableRoute.IRouteTransitionInvoker, MyRouteTransitionInvoker>();`

gives the following error: 

`The type or namespace name 'MyRouteTransitionInvoker' could not be found (are you missing a using directive or an assembly reference?)	PlannerApp-V2	C:\Users\Ricardo\source\repos\PlannerApp-V2\src\PlannerApp-V2\PlannerApp-V2\Program.cs	10	Active
`

**Comment by JByfordRew** [comment] 2022-03-02 07:02
Hi, sorry to hear you had difficulties getting it working.  I believe this is caused by not getting the package and/or not adding `@using BlazorTransitionableRoute` to the `_Imports.razor` file, the step before.  I am assuming a step was missed or done in error.  Closing this issue.  Kind regards.

**Closed by JByfordRew** 2022-03-02 07:02 UTC
